spring.application.name=springai
server.port=8082

# spring.ai.chat.client.enabled=false
# API KEY should come from the environment for local/test runs
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.openai.chat.options.temperature=1

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# OLLAMA EMBEDDING MODEL
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.model.chat=openai
spring.ai.model.embedding=ollama
#DB configuration

spring.datasource.url=jdbc:mariadb://localhost:3308/springai
spring.datasource.username=root
spring.datasource.password=root
# spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS

spring.ai.vectorstore.mariadb.initialize-schema=true
spring.ai.vectorstore.mariadb.distance-type=COSINE
# spring.ai.vectorstore.mariadb.dimensions=3072
spring.ai.vectorstore.mariadb.dimensions=768